on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the entire repo is checked out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose unzip wget jq

      - name: Verify docker-compose.yaml exists
        run: ls -l voting-app/  # Adjust the path as needed

      - name: Pull necessary images
        run: |
          docker pull postgres:alpine
          docker pull redis:alpine
          docker pull dockersamples/examplevotingapp_vote
          docker pull dockersamples/examplevotingapp_worker
          docker pull dockersamples/examplevotingapp_result

      - name: Build and run the application
        run: |
          cd voting-app  # Adjust if needed
          docker-compose up -d  # Start your services (assumed to expose ports 5000 and 5001)

      - name: Wait for the application to be ready
        run: sleep 30  # Give time for services to start

      - name: Install Ngrok (latest version)
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/
          ngrok version

      - name: Setup Ngrok authtoken
        run: ngrok authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start Ngrok tunnels for ports 5000 and 5001
        run: |
          # Set NGROK_WEB_ADDR using environment variable to specify the web interface for each instance.
          nohup env NGROK_WEB_ADDR=127.0.0.1:4040 ngrok http 5000 > ngrok5000.log 2>&1 &
          nohup env NGROK_WEB_ADDR=127.0.0.1:4041 ngrok http 5001 > ngrok5001.log 2>&1 &
          sleep 10  # Allow time for Ngrok to establish tunnels
          echo "Ngrok tunnel for port 5000 started. Log snippet:"
          head -n 10 ngrok5000.log
          echo "Ngrok tunnel for port 5001 started. Log snippet:"
          head -n 10 ngrok5001.log

      - name: Display public URLs for both tunnels
        run: |
          echo "Fetching Ngrok public URL for port 5000..."
          curl --silent http://127.0.0.1:4040/api/tunnels | jq
          echo "Fetching Ngrok public URL for port 5001..."
          curl --silent http://127.0.0.1:4041/api/tunnels | jq

      - name: Keep tunnels alive for debugging (sleep for 6 minutes)
        run: sleep 360
