name: Build and Deploy Voting App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the entire repo is checked out

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          cd voting-app  # Adjust if needed
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository }}/voting-app:latest .
          docker push ghcr.io/${{ github.repository }}/voting-app:latest

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose unzip wget jq

      - name: Pull necessary images
        run: |
          docker pull postgres:alpine
          docker pull redis:alpine
          docker pull ghcr.io/${{ github.repository }}/voting-app:latest

      - name: Deploy the Application
        run: |
          cd voting-app  # Adjust if needed
          docker-compose down  # Stop any running instances
          docker-compose up -d  # Start services

      - name: Wait for the application to be ready
        run: sleep 30  # Allow services to initialize

      - name: Install and configure Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/
          ngrok authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start Ngrok tunnels
        run: |
          nohup ngrok http 5000 --log=stdout > ngrok5000.log 2>&1 &
          nohup ngrok http 5001 --log=stdout > ngrok5001.log 2>&1 &
          sleep 10
          echo "Ngrok tunnel for port 5000:"
          curl --silent http://127.0.0.1:4040/api/tunnels | jq
          echo "Ngrok tunnel for port 5001:"
          curl --silent http://127.0.0.1:4041/api/tunnels | jq
